name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup git repository
      uses: actions/checkout@v3
    - name: Setup toolchain
      run: sudo apt update -y; sudo apt install -y gcc-multilib g++-multilib valgrind
    - name: Build
      run: make profile=release
